### ISSUE TITLE
AttributeError [nightly]

### ISSUE THREAD

**Issue by KiraSlith** [wizzomafizzo/starcheat#291]
Starbound version: 1.0.1 (Latest as of 7/25/16)
Starcheat Build: 55f5867-win32 & win64 (master-b51) persistent back into 72bb13e7
Mods(?): Avali Triage, Xbawks, Improved Containers, Extended Songbook, Detailed Species
OS: Windows 10 Home x64 

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 176, in __init__
  File "build\gui\mainwindow.py", line 555, in open_file
  File "build\gui\mainwindow.py", line 261, in update
  File "build\gui\mainwindow.py", line 719, in update_bag
  File "build\gui\common.py", line 116, in __init__
  File "build\gui\common.py", line 63, in inv_icon
  File "build\assets\items.py", line 141, in get_item_icon
AttributeError: 'list' object has no attribute 'split'

I didn't see it listed here anywhere and I assume its a known bug, but just in-case I might as well post this here anyway for posterity's sake if nothing else.

**Comment by medeor413** [comment]
Yeah. I've seen this error a few times. Mind sening me your player file(s)?

**Comment by medeor413** [comment]
Fixed by a1b048de21496aba0b99d5f3e74bc67e3b766f8f

**Comment by ColeTheKing** [comment]
I'm still getting this error myself, almost word for word in the latest nightly build (29aacb53, master b-58).

`Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 175, in __init__
  File "build\gui\mainwindow.py", line 552, in open_file
  File "build\gui\mainwindow.py", line 258, in update
  File "build\gui\mainwindow.py", line 716, in update_bag
  File "build\gui\common.py", line 116, in __init__
  File "build\gui\common.py", line 63, in inv_icon
  File "build\assets\items.py", line 141, in get_item_icon
AttributeError: 'list' object has no attribute 'split'`

Same Starbound version as OP, same OS, no mods installed.

**Comment by medeor413** [comment]
I guess not fixed then...

**Comment by Lknechtli** [comment]
```diff
diff --git a/starcheat/assets/items.py b/starcheat/assets/items.py
index 61533a9..3a96f0b 100644
--- a/starcheat/assets/items.py
+++ b/starcheat/assets/items.py
@@ -138,7 +138,10 @@ class Items(object):
             return
 
         icon_file = item[0]["inventoryIcon"]
-        icon_name = icon_file.split(':')
+        if not isinstance(icon_file, str):
+            icon_name =  [icon_file[0]['image']]
+        else:
+            icon_name = icon_file.split(':')
         if len(icon_name) < 2:
             icon_name = [icon_name[0], 0]
```
This fixed it locally for me.
Don't have the time to do a proper PR, but it's a small enough fix.

**Comment by medeor413** [comment]
Thank you much for the snippet, I'll put it in ASAP.

**Comment by medeor413** [comment]
[Here's](https://ci.appveyor.com/api/buildjobs/umt2qe3mxck4a9l5/artifacts/dist/starcheat-b30271c-win64.zip) the build with the fix included. Please try this and tell me if it solves your issue.

**Comment by kurisubrooks** [comment]
How did you come across this error? What were you doing when this error appeared?

**Comment by ColeTheKing** [comment]
Seems to be working fine for me, no more crashing.

**Comment by kurisubrooks** [comment]
Awesome! Can we close this @chrmoritz ?
